# Generated by Django 3.2 on 2021-04-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likequestion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='likequestion',
            name='question',
        ),
        migrations.DeleteModel(
            name='LikeAnswer',
        ),
        migrations.DeleteModel(
            name='LikeQuestion',
        ),
    ]
