# Generated by Django 3.2 on 2021-04-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerLike',
            new_name='LikeAnswer',
        ),
        migrations.RenameModel(
            old_name='QuestionLike',
            new_name='LikeQuestion',
        ),
    ]
