# Generated by Django 3.2 on 2021-04-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210420_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likeanswer',
            options={'verbose_name': 'Like (answer)', 'verbose_name_plural': 'Likes (answer)'},
        ),
        migrations.AlterModelOptions(
            name='likequestion',
            options={'verbose_name': 'Like (question)', 'verbose_name_plural': 'Likes (question)'},
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
