# Generated by Django 3.2 on 2021-06-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
