# Generated by Django 3.2 on 2021-04-20 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_likequestion_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likeanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='likequestion',
            options={},
        ),
        migrations.RemoveField(
            model_name='likeanswer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='likeanswer',
            name='like_status',
        ),
        migrations.RemoveField(
            model_name='likeanswer',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='likequestion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='likequestion',
            name='like_status',
        ),
        migrations.RemoveField(
            model_name='likequestion',
            name='profile',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_status', models.IntegerField(choices=[(1, 'LIKE'), (-1, 'DISLIKE')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.AddField(
            model_name='likeanswer',
            name='like_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.like'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likequestion',
            name='like_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.like'),
            preserve_default=False,
        ),
    ]
