# Generated by Django 3.2 on 2021-04-20 15:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210420_1422'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
